#!/usr/bin/env bash
# deploy.sh — Deploy daily-brief to a local test directory.
# Does NOT modify this source repo. Safe to run anytime.
#
# Usage:
#   ./deploy.sh                  # Deploy to ~/Scripts/daily-brief
#   ./deploy.sh ~/mydir          # Deploy to a custom path
#   ./deploy.sh --run            # Deploy + run the pipeline immediately
#   ./deploy.sh --dry-run        # Show what would be fetched (no email sent)
#   ./deploy.sh --render-only    # Fetch + score + render, save HTML, no email
#   ./deploy.sh --help

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_DEPLOY="$HOME/Scripts/daily-brief"
DEPLOY_DIR="${1:-$DEFAULT_DEPLOY}"
MODE="deploy"

# Parse flags
for arg in "$@"; do
  case "$arg" in
    --run)        MODE="run" ;;
    --dry-run)    MODE="dry-run" ;;
    --render-only) MODE="render-only" ;;
    --help|-h)    MODE="help" ;;
    --*)          echo "Unknown flag: $arg" >&2; exit 1 ;;
    *)            DEPLOY_DIR="$arg" ;;
  esac
done

# Strip flags from DEPLOY_DIR if it was set to a flag
if [[ "$DEPLOY_DIR" == --* ]]; then
  DEPLOY_DIR="$DEFAULT_DEPLOY"
fi

# ── Help ──────────────────────────────────────────────────────────────────────
if [[ "$MODE" == "help" ]]; then
  cat <<EOF
Daily Brief — Local Deployment Script

Usage:
  ./deploy.sh [TARGET_DIR] [MODE]

TARGET_DIR (optional):
  Directory to deploy into. Default: ~/Scripts/daily-brief

Modes:
  (none)          Deploy/sync files only. No pipeline run.
  --run           Deploy, then run the full pipeline (sends email).
  --dry-run       Deploy, fetch articles, score them, print summary — no email.
  --render-only   Deploy, run pipeline, save digest.html locally — no email.
  --help          Show this message.

First-time setup:
  1. Run: ./deploy.sh
  2. Edit: ~/Scripts/daily-brief/.env  (fill in your API keys)
  3. Test: ./deploy.sh --dry-run
  4. Send:  ./deploy.sh --run

Examples:
  ./deploy.sh                        # Sync files to ~/Scripts/daily-brief
  ./deploy.sh /tmp/brief-test --run  # Deploy to custom path and run
  ./deploy.sh --dry-run              # Test without sending email
EOF
  exit 0
fi

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; RESET='\033[0m'; BOLD='\033[1m'
info()  { echo -e "${GREEN}▶${RESET} $*"; }
warn()  { echo -e "${YELLOW}⚠${RESET}  $*"; }
error() { echo -e "${RED}✖${RESET}  $*" >&2; }
header(){ echo -e "\n${BOLD}$*${RESET}"; }

# ── Deploy ────────────────────────────────────────────────────────────────────
header "Daily Brief — Local Deployment"
info "Source : $SOURCE_DIR"
info "Target : $DEPLOY_DIR"

mkdir -p "$DEPLOY_DIR"

# ── Protect .env ──────────────────────────────────────────────────────────────
# .env is NEVER written or deleted by this script once it exists.
ENV_FILE="$DEPLOY_DIR/.env"
ENV_EXISTS=false
if [[ -f "$ENV_FILE" ]]; then
  ENV_EXISTS=true
  info ".env exists — will not touch it"
fi

# Rsync source files. .env is explicitly excluded at the rsync level as a
# second layer of protection, regardless of the ENV_EXISTS check above.
rsync -a --delete \
  --exclude='.git/' \
  --exclude='.env' \
  --exclude='__pycache__/' \
  --exclude='*.pyc' \
  --exclude='.venv/' \
  --exclude='venv/' \
  --exclude='deploy.sh' \
  "$SOURCE_DIR/" "$DEPLOY_DIR/"

info "Files synced"

# Sanity check: .env must still be present if it was there before
if [[ "$ENV_EXISTS" == true && ! -f "$ENV_FILE" ]]; then
  error ".env was deleted during rsync — this should never happen. Aborting."
  exit 1
fi

# First-time only: seed .env from .env.example
if [[ "$ENV_EXISTS" == false ]]; then
  cp "$SOURCE_DIR/.env.example" "$ENV_FILE"
  warn ".env created at $ENV_FILE"
  warn "Fill in your API keys before running the pipeline."
fi

# ── Python venv ───────────────────────────────────────────────────────────────
VENV="$DEPLOY_DIR/.venv"
if [[ ! -d "$VENV" ]]; then
  info "Creating Python virtual environment..."
  python3 -m venv "$VENV"
fi

info "Installing dependencies..."
"$VENV/bin/pip" install -q -r "$DEPLOY_DIR/requirements.txt"

# ── Write local runner script ─────────────────────────────────────────────────
# run.sh is a thin env-loader only. All mode logic lives in main.py --mode.
RUNNER="$DEPLOY_DIR/run.sh"
cat > "$RUNNER" <<'RUNNER_EOF'
#!/usr/bin/env bash
# run.sh — Load .env and pass all arguments to main.py.
# Usage: ./run.sh [--mode full|dry-run|render-only|update-prefs]
# Generated by deploy.sh — safe to re-deploy, .env is never touched.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ ! -f "$SCRIPT_DIR/.env" ]] && echo "ERROR: $SCRIPT_DIR/.env not found. Copy .env.example and fill in your keys." >&2 && exit 1
set -o allexport; source "$SCRIPT_DIR/.env"; set +o allexport
exec "$SCRIPT_DIR/.venv/bin/python" "$SCRIPT_DIR/src/main.py" "$@"
RUNNER_EOF
chmod +x "$RUNNER"

# ── Summary ───────────────────────────────────────────────────────────────────
header "Deployment complete"
echo ""
echo -e "  ${BOLD}Location:${RESET}  $DEPLOY_DIR"
echo -e "  ${BOLD}Env file:${RESET}  $ENV_FILE"
echo ""
echo -e "  ${BOLD}Next steps:${RESET}"

if grep -q "sk-ant-\.\.\." "$ENV_FILE" 2>/dev/null || grep -q "your-nyt-key-here" "$ENV_FILE" 2>/dev/null; then
  echo -e "  ${YELLOW}1. Fill in API keys:${RESET}  edit $ENV_FILE"
  echo    "  2. Dry run:           $DEPLOY_DIR/run.sh --mode dry-run"
  echo    "  3. Preview email:     $DEPLOY_DIR/run.sh --mode render-only"
  echo    "  4. Full send:         $DEPLOY_DIR/run.sh --mode full"
else
  echo    "  Dry run:              $DEPLOY_DIR/run.sh --mode dry-run"
  echo    "  Preview email HTML:   $DEPLOY_DIR/run.sh --mode render-only"
  echo    "  Send email:           $DEPLOY_DIR/run.sh (default: full)"
  echo    "  Update preferences:   $DEPLOY_DIR/run.sh --mode update-prefs"
fi
echo ""

# If a run mode was requested, execute it now
if [[ "$MODE" == "run" ]]; then
  header "Running pipeline..."
  "$RUNNER"
elif [[ "$MODE" == "dry-run" ]]; then
  header "Dry run..."
  "$RUNNER" --mode dry-run
elif [[ "$MODE" == "render-only" ]]; then
  header "Rendering preview..."
  "$RUNNER" --mode render-only
fi
